server:
  port: 8082
spring:
  application:
    name: catalog-service
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        enabled: true
        service-name: catalog-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-url: http://host.docker.internal:8082/actuator/health
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: mysecurepassword123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
    version: openapi_3_0
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json