server:
  port: 8087
spring:
  application:
    name: identity-service
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        enabled: true
        service-name: identity-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-url: http://host.docker.internal:8087/actuator/health
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: mysecurepassword123

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: user-notification-exchange
      routing-key: user.notification
jwt:
  secret-key: $2y$12$HUqVeRx/yQGWi92jQi1hjO/S/M1vT9VmiDNTMvw8OC9pmz5RIofwO

user-service:
    urlCreateUser: http://localhost:8086/user-profile

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
