server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        enabled: true
        health-check-path: /actuator/health
        prefer-ip-address: true
        service-name: api-gateway
        health-check-url: http://host.docker.internal:8080/actuator/health
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: http://localhost:8081
          predicates:
            - Path=/booking-service/**
          filters:
            - StripPrefix=1
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/catalog-service/**
        - id: loyalty-service
          uri: http://localhost:8083
          predicates:
            - Path=/loyalty-service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notification-service/**
        - id: pet-service
          uri: http://localhost:8085
          predicates:
            - Path=/pet-service/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: identity-service
          uri: http://localhost:8087
          predicates:
            - Path=/identity-service/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: http://localhost:8088
          predicates:
            - Path=/search-service/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: booking-service
        url: /booking-service/v3/api-docs
      - name: catalog-service
        url: /catalog-service/v3/api-docs
      - name: identity-service
        url: /identity-service/v3/api-docs
      - name: loyalty-service
        url: /loyalty-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs
      - name: pet-service
        url: /pet-service/v3/api-docs
      - name: search-service
        url: /search-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
  api-docs:
    path: /v3/api-docs
