server:
  port: 8088
spring:
  application:
    name: search-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # Cho phép deserialize tất cả DTO

  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        enabled: true
        service-name: search-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-url: http://host.docker.internal:8088/actuator/health

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: mysecurepassword123

